### ISSUE TITLE
Unable to Import Framework in Swift

### ISSUE THREAD

**Issue by ghost** [momentlib/swiftFramework#1]
Even after adding the framework, and adding framework search paths and everything, import is not recognising MomentLib.

**Comment by ghost** [comment]
[Ninja Web Squad A OKRs.pptx](https://github.com/momentlib/swiftFramework/files/5652547/Ninja.Web.Squad.A.OKRs.pptx)

**Comment by ghost** [comment]
[PO Overview.pdf](https://github.com/momentlib/swiftFramework/files/5653715/PO.Overview.pdf)

**Comment by ghost** [comment]
![Uploading 0320E1CA-FF64-4DDF-B3D1-4A93DBDF3673.jpeg…]()

**Comment by ghost** [comment]
![22283FA0-5373-40D1-8E59-53BE42EA797F](https://user-images.githubusercontent.com/19385290/101438838-3af53680-3939-11eb-8f9e-d216cbfef774.jpeg)

**Comment by ghost** [comment]
![591AD4C4-07F1-410F-86B5-40B435FD37DE](https://user-images.githubusercontent.com/19385290/101438874-56f8d800-3939-11eb-8c2f-64d9fff6020c.jpeg)

**Comment by ghost** [comment]
[BacklogPlanning.xlsx](https://github.com/momentlib/swiftFramework/files/5702404/BacklogPlanning.xlsx)

**Comment by vividhneo** [comment]
[Uploading Web 3.0 and Ninja Squad V1.3-20201012.pptx…]()

**Comment by ghost** [comment]
[Web 3.0 and Ninja Squad V1.3-20201012.pptx](https://github.com/momentlib/swiftFramework/files/5702639/Web.3.0.and.Ninja.Squad.V1.3-20201012.pptx)

**Comment by ghost** [comment]
[Lock-ups.zip](https://github.com/momentlib/swiftFramework/files/5786646/Lock-ups.zip)

**Comment by ghost** [comment]
[Here for good.zip](https://github.com/momentlib/swiftFramework/files/5786651/Here.for.good.zip)
[Trustpoints.zip](https://github.com/momentlib/swiftFramework/files/5786652/Trustpoints.zip)
[Wordmarks.zip](https://github.com/momentlib/swiftFramework/files/5786653/Wordmarks.zip)

**Comment by ghost** [comment]
[One slider123.pptx](https://github.com/momentlib/swiftFramework/files/5812233/One.slider123.pptx)

**Comment by ghost** [comment]
[One.slider123.pptx](https://github.com/momentlib/swiftFramework/files/5812244/One.slider123.pptx)

**Comment by ghost** [comment]
[Presentation5 [Auto-saved].zip](https://github.com/momentlib/swiftFramework/files/5843630/Presentation5.Auto-saved.zip)
